test: boot: measurement: Fix compilation for non-sandbox builds
asm/io.h provides map_to_sysmem() only for the sandbox. Other targets
fail the build with

../test/boot/measurement.c: In function ‘measure’:
../test/boot/measurement.c:30:33: error: implicit declaration of function ‘map_to_sysmem’; did you mean ‘map_physmem’? [-Wimplicit-function-declaration]
   30 |         images.os.image_start = map_to_sysmem(kernel);
      |                                 ^~~~~~~~~~~~~
      |                                 map_physmem

Use the proper header that will pull asm/io.h only where needed.

Signed-off-by: Jan Kiszka <jan.kiszka@siemens.com>
(cherry picked from commit f92bd784f6ce15aac66e89ab4c17349af18d4ddd)