Gitlab CI: sage: Disable test_net_tftpboot_boot on Raspberry Pi 4 for now
With commit 623f6c5b6ab7 ("boot: image-fdt: free old dtb reservations")
we now get:
ERROR: freeing fdt memory region failed (addr=3ef667e0 size=36 flags=2): -1
ERROR: freeing fdt memory region failed (addr=3ef663a0 size=400 flags=2): -1
on console when booting, which is non-fatal but leads to the test
failing. Disable this test for now.

Acked-by: Ilias Apalodimas <ilias.apalodimas@linaro.org>
Signed-off-by: Tom Rini <trini@konsulko.com>
(cherry picked from commit 06c866fee0052579dbd27456fac425d002d44a80)