fpga: Gate FPGA_VERSALPL on ZYNQMP_FIRMWARE
drivers/fpga/versalpl.c issues Xilinx firmware calls via
xilinx_pm_request(), which lives in drivers/firmware/firmware-zynqmp.c
and is compiled only when CONFIG_ZYNQMP_FIRMWARE is enabled.
allyesconfig therefore fails to link:

    drivers/fpga/versalpl.c: undefined reference to 'xilinx_pm_request'

Add the missing Kconfig dependency.

Signed-off-by: Simon Glass <sjg@chromium.org>