rockchip: only build GPT capsule update helpers with PARTITION_TYPE_GUID
The GPT-based capsule update helpers match updatable images by
partition type GUID and fail to build if PARTITION_TYPE_GUID is not
enabled:

  arch/arm/mach-rockchip/board.c:50:29: error: 'struct disk_partition'
  has no member named 'type_guid'

Boards which keep their firmware on SPI-NOR use a static dfu_string
instead of scanning GPT partitions and have no use for this code, so
guard it accordingly.

Signed-off-by: Daniel Golle <daniel@makrotopia.org>
Reviewed-by: Quentin Schulz <quentin.schulz@cherry.de>
Fixes: bea9267d7e6d ("rockchip: capsule: Add functions for supporting capsule updates")
Link: https://patch.msgid.link/af0ac32e2bf603c39f490f15fe62319fd73c5282.1784423864.git.daniel@makrotopia.org
Signed-off-by: Quentin Schulz <u-boot@0leil.net>
(cherry picked from commit 3bc0f812735350831c6b63fa163c02ecdf61694c)